### ISSUE TITLE
Idea: Support Renaming Unresolved Variables

### ISSUE THREAD

**Issue by hediet** [p42ai/refactor-vscode#25]
After copy&pasting, I ended up with this code:

```ts
public extendInputRange(extendedInputRange: LineRange): LineRangeMapping {

    const startDelta = extendedInputRange.startLineNumber - l.inputRange.startLineNumber;
    const endDelta = extendedInputRange.endLineNumberExclusive - l.inputRange.endLineNumberExclusive;
    return new LineRangeMapping(
        inputRange,
        new LineRange(
            l.outputRange.startLineNumber + startDelta,
            l.outputRange.lineCount - startDelta + endDelta
        )
    );
}
```

Now I would like to replace `l` with `this`.
This is not very easy to do.

It would be awesome if I could rename `l` to `this`.

**Comment by lgrammel** [comment]
Thanks for the suggestion! I'll think about how to best resolve this with a single refactoring.

It's already fairly easy to do with a combo:
1. extract `l`
2. change it's value
3. inline `l`

![example-20220612](https://user-images.githubusercontent.com/205036/173237344-dd587bd4-047d-469d-8765-a06622de8abf.gif)

**Comment by lgrammel** [comment]
I thought more about this and evaluated various ways of achieving this. It turns out you can easily achieve this by using multiple cursors:

1. select "l"
2. start multiple cursors with ⇧⌘L
3. change to `this`
4. end multiple cursors with Esc

Since there is a pretty elegant built-in solution, I'm wondering how P42 could improve on this.

**Comment by lgrammel** [comment]
Ah, right. One idea I have is a `replace expression` code assist where you could select an expression, invoke the action, and then all it's occurrences would be replaced with a text that you'd enter in a text box. Would that be closer to what you imagine?

**Comment by hediet** [comment]
That would be cool!

**Comment by lgrammel** [comment]
I've added a "Select expression occurrences" code action in `v1.117.0`. When you select an expression (selection boundaries must match expression), you can invoke the P42 action menu and start a multi-cursor selection on all occurrences:

![action-select-expression-occurrences](https://user-images.githubusercontent.com/205036/173574154-187dbc52-f83b-4acc-8f28-adf5320731e6.gif)

This is different from the VS Code standard multi-cursor, because it checks that the expression occurrences use the same variables, `this` context, etc.
